# Generated by Django 5.2.3 on 2025-06-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseimage',
            name='image',
        ),
        migrations.AddField(
            model_name='houseimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='baths',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='house',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
